### ISSUE TITLE
Drip drop animation in Jupyter notebook

### ISSUE THREAD

**Issue by LePingKYXK** [rougier/matplotlib-tutorial#12]
Hi, thanks for sharing this excellent tutorial.
I am learning it via Jupyter notebook, but I found that the drip drop animation code could not update automatically. Is there any suggestion?
Indeed, it works in python IDE. 
Thanks again.

**Comment by rougier** [comment]
I'm not familiar enough with jupyte notebook but I'm not sure it's immediately compatible with animation.

**Comment by StefRe** [comment]
To show the animation in the Jupyter notebook you'll have to render it into an html video:
```
from IPython.display import HTML
HTML(animation.to_html5_video())
```

see [Render the Animation](https://colab.research.google.com/github/jckantor/CBE30338/blob/master/docs/A.03-Animation-in-Jupyter-Notebooks.ipynb#scrollTo=MWQoXmEk6W75) for further details.

**Comment by rougier** [comment]
@StefRe Thanks for the hint. I would be worth to be mentioned in the tutorial. Could you make a PR (in the animation section) ?
