### ISSUE TITLE
Python plot similar to Matlab's stackedplot()

### ISSUE THREAD

**Issue by addarnr** [rougier/matplotlib-tutorial#16]
Hello,
Is there a plot function available in Python that is same as Matlab's stackedplot()? 
stackedplot() in Matlab can line plot several variables with the same X axis and are stacked vertically. Additionally, there is a scope in this plot that shows the value of all variables for a given X just by moving the cursor (please see the plot below). I have been able to generate subplots in Python with no issues, however, not able to add a scope like this that shows the value of all variables by moving the cursor. Is this feature available in Python?

Thanks much for your help in advance!

![stackedplot scope2](https://user-images.githubusercontent.com/34237024/89841228-09f62800-db38-11ea-8358-0853c427fbe4.png)

**Comment by rougier** [comment]
Hi @addarnr 

You should ask your question on the matplotlib discourse site: https://discourse.matplotlib.org/

**Comment by addarnr** [comment]
Hello,
Ok. Thanks!
