### ISSUE TITLE
A typo in your blog "Matplotlib tutorial"

### ISSUE THREAD

**Issue by JohnCoconut** [rougier/matplotlib-tutorial#2]
I understand that I should not post a typo in your blog here, but this is the only way I can contact you, since your blog points here.

In your blog "Matplotlib tutorial", chapter "Simple Plot", section "Instantiating defaults", `# savefig("../figures/exercice_2.png",dpi=72)` could be changed to `plt.savefig("../figures/exercice_2.png",dpi=72)`.  You might have just missed `plt` in your code.

I really appreciate your tutorial. It's the best I could find on the web.

**Comment by rougier** [comment]
Thanks and this just the right way to report an issue actually. Could you make a Pull Request such as your name appears in the contributors (If you don't know how, I can explain) ?

**Comment by ElJdP** [comment]
@JohnCoconut Hasn't this been fixed? If so, you can close this issue. I couldn't find the error but would be ready to open a PR if not.
