### ISSUE TITLE
Broken links in README.rst

### ISSUE THREAD

**Issue by CaptSolo** [rougier/matplotlib-tutorial#28]
Thank you for a great tutorial!

There are broken internal links in README.rst (under the heading ["Other Types of Plots"](https://github.com/rougier/matplotlib-tutorial/blob/master/README.rst#other-types-of-plots) after the earthquake example).

For example: image with text "Regular plot" points to a URL that returns 404 Not Found error:
- `https://github.com/rougier/matplotlib-tutorial/blob/master/%60Regular%20Plots%60_`

A working link for the section "Regular plot" is:
- `https://github.com/rougier/matplotlib-tutorial/blob/master/README.rst#regular-plots`

**Comment by rougier** [comment]
Thanks. Can you make a PR?

**Comment by CaptSolo** [comment]
> Thanks. Can you make a PR?

Done.

**Comment by rougier** [comment]
Merged!
