### ISSUE TITLE
errata on http://www.labri.fr/perso/nrougier/teaching/matplotlib/#other-types-of-plots

### ISSUE THREAD

**Issue by LukeSkypewalker** [rougier/matplotlib-tutorial#5]
Hi Nicolas,
Great tutorial !

I've used version from http://www.labri.fr/perso/nrougier/teaching/matplotlib/
and there are errata in the #other-types-of-plots

http://www.labri.fr/perso/nrougier/teaching/matplotlib/#other-types-of-plots
import maplotlib.pyplot as plt
should be:
import ma**t**plotlib.pyplot as plt
in all examples

in GitHub version it is just fine

**Comment by rougier** [comment]
Thank @LukeSkypewalker. I need to  update the website.

**Comment by rougier** [comment]
Done !
